vim.opt.autoindent = true
vim.opt.backup = false
vim.opt.cindent = true
vim.opt.clipboard = "unnamedplus" -- sync with system clipboard
vim.opt.cmdheight = 1 -- height of the cmdline
vim.opt.completeopt = { "menuone", "noselect" }
vim.opt.conceallevel = 0
vim.opt.cursorline = true
vim.opt.eadirection = "hor"
vim.opt.expandtab = true
vim.opt.fileencoding = "utf-8"
vim.opt.foldmethod = "manual"
vim.opt.grepformat = vim.opt.grepformat ^ { "%f:%l:%c:%m" }
vim.opt.grepprg = [[rg --hidden --glob "!.git" --no-heading --smart-case --vimgrep --follow $*]]
vim.opt.history = 50
vim.opt.hlsearch = true
vim.opt.ignorecase = true
vim.opt.laststatus = 3
vim.opt.list = true
vim.opt.mouse = "a"
vim.opt.number = true
vim.opt.numberwidth = 4
vim.opt.pumheight = 10
-- vim.opt.relativenumber = true
vim.opt.scrolloff = 4
vim.opt.shiftwidth = 2
vim.opt.showmode = false -- disable mode indicator in cmdline
-- vim.opt.showtabline = 2
vim.opt.sidescrolloff = 4
-- vim.opt.signcolumn = "yes"
vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.smarttab = true
vim.opt.softtabstop = -1 -- If negative, shiftwidth value is used
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.swapfile = false
vim.opt.switchbuf = "useopen,uselast"
vim.opt.tabstop = 2
vim.opt.termguicolors = true
vim.opt.textwidth = 300
vim.opt.timeoutlen = 500
vim.opt.undofile = true
vim.opt.updatetime = 200
vim.opt.wildmode = "longest:full,full" -- Command-line completion mode
vim.opt.wrap = true
vim.opt.writebackup = false

vim.opt.listchars = {
    eol = "↵",
    tab = " →",
    space = "·",
    multispace = "····",
    lead = " ",
    trail = "·",
    extends = "▸",
    precedes = "◂",
    nbsp = "◇",
}

vim.opt.fillchars = {
  vert = " ",
  fold = " ",
  eob = " ",
  diff = "░",
  msgsep = "‾",
  foldopen = "▾",
  foldsep = "|",
  foldclose = "▸",
}
