SELECT *
FROM `subsidiaries`
WHERE exists(SELECT *
             FROM `subsidiaries_desks`
             WHERE `subsidiaries_desks`.`subsidiary_id` = `subsidiaries`.`id` AND exists(SELECT *
                                                                                         FROM
                                                                                           `cashiers`
                                                                                         WHERE
                                                                                           `subsidiaries_desks`.`cashier_id`
                                                                                           =
                                                                                           `cashiers`.`id`
                                                                                           AND
                                                                                           `authorized`
                                                                                           RLIKE "\D1\D"
                                                                                           AND
                                                                                           `cashiers`.`deleted_at`
                                                                                           IS NULL))
      AND `subsidiaries`.`deleted_at` IS NULL
;-- -. . -..- - / . -. - .-. -.--
UPDATE oramaCustomers.customers SET nick = 'apack', created_at = '2016-09-06 23:11:25', updated_at = '2016-09-06 23:11:25', deleted_at = null, invoice_number = 1, un_invoice_number = 1, full_name = 'Instalación de un cliente con panel', code = '49910', short_name = 'CLIENTE', invoice_format = 'F-%''.05d-C', un_invoice_format = 'NC-%''.05d-C', web = 'http://panel.cliente.localwamp.dev/', emails = '[{"type":"Informaci\\u00f3n","email":"info@orama.com.mx"},{"type":"Contacto","email":"contacto@orama.com.mx"},{"type":"Inscripciones","email":"inscripciones@orama.com.mx"}]', phones = '[{"type":"Facturaci\\u00f3n","phone":"+52 (33) 1522 2777, ext: 26"},{"type":"Administrativo","phone":"+52 (33) 1522 2777, ext: 26"},{"type":"Contacto","phone":"+52 (33) 1522 2777, ext: 26"}]', contract = '{"backup":0,"historic":4.5,"active":{"0":9,"100":9,"300":8,"500":7,"750":6},"billing":{"taxid":"XAXX010101000","name":"Cliente muestra de Orama","address":{"direction":{"street":"Calle","out_number":"exterior","inside_number":"interior","suburb":"Colonia"},"zip":"c\\u00f3digo postal","location":{"municipality":"Municipio","city":"Ciudad","state":"C\\u00f3digo de estado","country":"C\\u00f3digo de pa\\u00eds"}},"phones":[{"type":"Facturaci\\u00f3n","phone":"+52 (33) 1522 2777, ext: 26"}],"emails":[{"type":"Facturaci\\u00f3n","email":"facturas@orama.com.mx"}]}}', invoices = '{"taxid":"XAXX010101000","name":"Cliente muestra de Orama","address":{"direction":{"street":"Calle","out_number":"exterior","inside_number":"interior","suburb":"Colonia"},"zip":"c\\u00f3digo postal","location":{"municipality":"Municipio","city":"Ciudad","state":"C\\u00f3digo de estado","country":"C\\u00f3digo de pa\\u00eds"},"phones":[{"type":"Facturaci\\u00f3n","phone":"+52 (33) 1522 2777, ext: 26"}],"emails":[{"type":"Facturaci\\u00f3n","email":"facturas@orama.mx"}]},"public":{"taxid":"XAXX010101000","business_name":"Publico en general","address":{"direction":{"street":"Calle","out_number":"exterior","inside_number":"interior","suburb":"Colonia"},"zip":"c\\u00f3digo postal","location":{"municipality":"Municipio","city":"Ciudad","state":"C\\u00f3digo de estado","country":"C\\u00f3digo de pa\\u00eds"},"phones":[{"type":"Facturaci\\u00f3n","phone":"+52 (33) 1522 2777, ext: 26"}]},"email":"facturas@orama.mx"},"certificate":"Cadena de certificado","taxation":"PERSONA MORAL","key":"Cadena de certificado","validity":{"start_at":"2016-04-04T00:00:00-0600","end_at":"2017-04-04T00:00:00-0600"},"locale":"cfdi","cfdi":{"api":{"class":"InterScape","url":"http:\\/\\/www.scapebusiness.mx\\/AppFactura.asmx?wsdl","user":"Usuario\\/RFC","password":"contrase\\u00f1a"}}}', config = '{"banks":{"BanBajio":{"TipoDeConcepto":{"service":"###","reference":"###","name":"Nombre del concepto","account":"###"}}}}', `database` = '{"installation":{"driver":"mysql","host":"localhost","port":"3306","database":"apack_test","username":"apacktest","password":"apackTest1","charset":"utf8","collation":"utf8_unicode_ci","prefix":"","strict":false,"engine":null}}' WHERE id = 2
;-- -. . -..- - / . -. - .-. -.--
SELECT
  payments.*,
  level_id,
  student_id,
  SUM(student_payment_detail.amount)      AS level_amount,
  GROUP_CONCAT(student_payment_detail.id) AS payment_details
FROM `student_payment_detail`
  LEFT JOIN `payments` ON `payments`.`id` = `payment_id`
WHERE `payments`.`deleted_at` IS NULL AND
      `payed_at` BETWEEN '2016-10-01 00:00:00.000000' AND '2016-11-01 00:00:00.000000' AND
      `invoice_id` IS NULL
GROUP BY `level_id`, `payment_id`, `student_id`
;-- -. . -..- - / . -. - .-. -.--
SELECT DISTINCT
  `people`.*,
  `student_payments`.`payment_id`,
  `levels`.`structure_id` AS
    `level_id`
FROM `people`
  LEFT JOIN `student_tuitions` ON `people`.`id` = `student_tuitions`.`student_id`
  LEFT JOIN `student_payments` ON `student_tuitions`.`id` = `student_payments`.`student_tuition_id`
  LEFT JOIN `structure_tuitions` ON `student_tuitions`.`tuition_id` = `structure_tuitions`.`id`
  LEFT JOIN `levels` ON `structure_tuitions`.`structure_id` = `levels`.`structure_id` OR
                        `structure_tuitions`.`structure_id` = `levels`.`structure_id` OR
                        `structure_tuitions`.`decendants` = `levels`.`structure_id`
WHERE `people`.`deleted_at` IS NULL AND `payment_id` IN
                                        (
                                          75458,
                                          75423,
                                          75423,
                                          75554,
                                          75555,
                                          75402,
                                          75426,
                                          75586,
                                          75384,
                                          75391,
                                          75396,
                                          75410,
                                          75420,
                                          75430,
                                          75440,
                                          75488,
                                          75490,
                                          75532,
                                          75535,
                                          75541,
                                          75544,
                                          75613,
                                          75639,
                                          75667,
                                          75668,
                                          75668,
                                          75674,
                                          75678,
                                          75694,
                                          75696,
                                          75750,
                                          75394,
                                          75397,
                                          75398,
                                          75400,
                                          75404,
                                          75409,
                                          75411,
                                          75412,
                                          75413,
                                          75415,
                                          75418,
                                          75429,
                                          75429,
                                          75430,
                                          75432,
                                          75443,
                                          75450,
                                          75452,
                                          75454,
                                          75456,
                                          75475,
                                          75527,
                                          75528,
                                          75529,
                                          75530,
                                          75533,
                                          75552,
                                          75562,
                                          75562,
                                          75566,
                                          75568,
                                          75571,
                                          75582,
                                          75589,
                                          75604,
                                          75611,
                                          75621,
                                          75624,
                                          75634,
                                          75652,
                                          75654,
                                          75655,
                                          75674,
                                          75680,
                                          75682,
                                          75686,
                                          75688,
                                          75689,
                                          75694,
                                          75698,
                                          75707,
                                          75707,
                                          75708,
                                          75711,
                                          75728,
                                          75733,
                                          75736,
                                          75738,
                                          75742,
                                          75404,
                                          75407,
                                          75408,
                                          75414,
                                          75416,
                                          75418,
                                          75427,
                                          75433,
                                          75451,
                                          75460,
                                          75476,
                                          75476,
                                          75482,
                                          75489,
                                          75494,
                                          75516,
                                          75521,
                                          75579,
                                          75610,
                                          75623,
                                          75625,
                                          75629,
                                          75630,
                                          75650,
                                          75659,
                                          75665,
                                          75677,
                                          75683,
                                          75684,
                                          75687,
                                          75700,
                                          75704,
                                          75707,
                                          75719,
                                          75720,
                                          75737,
                                          75638,
                                          75724,
                                          75748,
                                          75749,
                                          75453,
                                          75524,
                                          75602,
                                          75647,
                                          75653,
                                          75672,
                                          75715,
                                          75729,
                                          75389,
                                          75418,
                                          75431,
                                          75444,
                                          75449,
                                          75484,
                                          75486,
                                          75487,
                                          75515,
                                          75525,
                                          75531,
                                          75539,
                                          75565,
                                          75569,
                                          75572,
                                          75573,
                                          75603,
                                          75620,
                                          75648,
                                          75657,
                                          75658,
                                          75672,
                                          75673,
                                          75673,
                                          75681,
                                          75726,
                                          75727,
                                          75732,
                                          75381,
                                          75389,
                                          75446,
                                          75447,
                                          75459,
                                          75522,
                                          75523,
                                          75526,
                                          75545,
                                          75574,
                                          75578,
                                          75628,
                                          75628,
                                          75640,
                                          75671,
                                          75673,
                                          75679,
                                          75726,
                                          75734,
                                          75380,
                                          75393,
                                          75401,
                                          75421,
                                          75422,
                                          75461,
                                          75473,
                                          75513,
                                          75543,
                                          75551,
                                          75553,
                                          75626,
                                          75627,
                                          75627,
                                          75646,
                                          75651,
                                          75660,
                                          75661,
                                          75671,
                                          75685,
                                          75690,
                                          75691,
                                          75704,
                                          75709,
                                          75715,
                                          75726,
                                          75735
                                        )
GROUP BY `people`.`id`, `student_payments`.`payment_id`
;-- -. . -..- - / . -. - .-. -.--
SELECT DISTINCT
  people.*,
  `student_payments`.`payment_id`,
  `levels`.`structure_id` AS `level_id`
FROM `people`
  LEFT JOIN `student_tuitions` ON `people`.`id` = `student_tuitions`.`student_id`
  LEFT JOIN `student_payments` ON `student_tuitions`.`id` = `student_payments`.`student_tuition_id`
  LEFT JOIN `structure_tuitions` ON `student_tuitions`.`tuition_id` = `structure_tuitions`.`id`
  LEFT JOIN `levels` ON `structure_tuitions`.`structure_id` = `levels`.`structure_id` OR
                        `structure_tuitions`.`structure_id` = `levels`.`structure_id` OR
                        `structure_tuitions`.`decendants` = `levels`.`structure_id`
WHERE `people`.`deleted_at` IS NULL AND `payment_id` IN
                                        (
                                          75458,
                                          75423,
                                          75423,
                                          75554,
                                          75555,
                                          75402,
                                          75426,
                                          75586,
                                          75384,
                                          75391,
                                          75396,
                                          75410,
                                          75420,
                                          75430,
                                          75440,
                                          75488,
                                          75490,
                                          75532,
                                          75535,
                                          75541,
                                          75544,
                                          75613,
                                          75639,
                                          75667,
                                          75668,
                                          75668,
                                          75674,
                                          75678,
                                          75694,
                                          75696,
                                          75750,
                                          75394,
                                          75397,
                                          75398,
                                          75400,
                                          75404,
                                          75409,
                                          75411,
                                          75412,
                                          75413,
                                          75415,
                                          75418,
                                          75429,
                                          75429,
                                          75430,
                                          75432,
                                          75443,
                                          75450,
                                          75452,
                                          75454,
                                          75456,
                                          75475,
                                          75527,
                                          75528,
                                          75529,
                                          75530,
                                          75533,
                                          75552,
                                          75562,
                                          75562,
                                          75566,
                                          75568,
                                          75571,
                                          75582,
                                          75589,
                                          75604,
                                          75611,
                                          75621,
                                          75624,
                                          75634,
                                          75652,
                                          75654,
                                          75655,
                                          75674,
                                          75680,
                                          75682,
                                          75686,
                                          75688,
                                          75689,
                                          75694,
                                          75698,
                                          75707,
                                          75707,
                                          75708,
                                          75711,
                                          75728,
                                          75733,
                                          75736,
                                          75738,
                                          75742,
                                          75404,
                                          75407,
                                          75408,
                                          75414,
                                          75416,
                                          75418,
                                          75427,
                                          75433,
                                          75451,
                                          75460,
                                          75476,
                                          75476,
                                          75482,
                                          75489,
                                          75494,
                                          75516,
                                          75521,
                                          75579,
                                          75610,
                                          75623,
                                          75625,
                                          75629,
                                          75630,
                                          75650,
                                          75659,
                                          75665,
                                          75677,
                                          75683,
                                          75684,
                                          75687,
                                          75700,
                                          75704,
                                          75707,
                                          75719,
                                          75720,
                                          75737,
                                          75638,
                                          75724,
                                          75748,
                                          75749,
                                          75453,
                                          75524,
                                          75602,
                                          75647,
                                          75653,
                                          75672,
                                          75715,
                                          75729,
                                          75389,
                                          75418,
                                          75431,
                                          75444,
                                          75449,
                                          75484,
                                          75486,
                                          75487,
                                          75515,
                                          75525,
                                          75531,
                                          75539,
                                          75565,
                                          75569,
                                          75572,
                                          75573,
                                          75603,
                                          75620,
                                          75648,
                                          75657,
                                          75658,
                                          75672,
                                          75673,
                                          75673,
                                          75681,
                                          75726,
                                          75727,
                                          75732,
                                          75381,
                                          75389,
                                          75446,
                                          75447,
                                          75459,
                                          75522,
                                          75523,
                                          75526,
                                          75545,
                                          75574,
                                          75578,
                                          75628,
                                          75628,
                                          75640,
                                          75671,
                                          75673,
                                          75679,
                                          75726,
                                          75734,
                                          75380,
                                          75393,
                                          75401,
                                          75421,
                                          75422,
                                          75461,
                                          75473,
                                          75513,
                                          75543,
                                          75551,
                                          75553,
                                          75626,
                                          75627,
                                          75627,
                                          75646,
                                          75651,
                                          75660,
                                          75661,
                                          75671,
                                          75685,
                                          75690,
                                          75691,
                                          75704,
                                          75709,
                                          75715,
                                          75726,
                                          75735
                                        )
GROUP BY `people`.`id`, `student_payments`.`payment_id`
;-- -. . -..- - / . -. - .-. -.--
UPDATE oramaCustomers.customers
SET nick         = 'apack', created_at = '2016-09-06 23:11:25', updated_at = '2016-09-06 23:11:25',
  deleted_at     = NULL, invoice_number = 1, un_invoice_number = 1,
  full_name      = 'Instalación de un cliente con panel', code = '49910', short_name = 'CLIENTE',
  invoice_format = 'F-%''.05d-C', un_invoice_format = 'NC-%''.05d-C',
  web            = 'http://panel.cliente.localwamp.dev/',
  emails         = '[{"type":"Informaci\\u00f3n","email":"info@orama.com.mx"},{"type":"Contacto","email":"contacto@orama.com.mx"},{"type":"Inscripciones","email":"inscripciones@orama.com.mx"}]',
  phones         = '[{"type":"Facturaci\\u00f3n","phone":"+52 (33) 1522 2777, ext: 26"},{"type":"Administrativo","phone":"+52 (33) 1522 2777, ext: 26"},{"type":"Contacto","phone":"+52 (33) 1522 2777, ext: 26"}]',
  contract       = '{"backup":0,"historic":4.5,"active":{"0":9,"100":9,"300":8,"500":7,"750":6},"billing":{"taxid":"XAXX010101000","name":"Cliente muestra de Orama","address":{"direction":{"street":"Calle","out_number":"exterior","inside_number":"interior","suburb":"Colonia"},"zip":"c\\u00f3digo postal","location":{"municipality":"Municipio","city":"Ciudad","state":"C\\u00f3digo de estado","country":"C\\u00f3digo de pa\\u00eds"}},"phones":[{"type":"Facturaci\\u00f3n","phone":"+52 (33) 1522 2777, ext: 26"}],"emails":[{"type":"Facturaci\\u00f3n","email":"facturas@orama.com.mx"}]}}',
  invoices       = '{"taxid":"XAXX010101000","name":"Cliente muestra de Orama","address":{"direction":{"street":"Calle","out_number":"exterior","inside_number":"interior","suburb":"Colonia"},"zip":"c\\u00f3digo postal","location":{"municipality":"Municipio","city":"Ciudad","state":"C\\u00f3digo de estado","country":"C\\u00f3digo de pa\\u00eds"},"phones":[{"type":"Facturaci\\u00f3n","phone":"+52 (33) 1522 2777, ext: 26"}],"emails":[{"type":"Facturaci\\u00f3n","email":"facturas@orama.mx"}]},"public":{"taxid":"XAXX010101000","business_name":"Publico en general","address":{"direction":{"street":"Calle","out_number":"exterior","inside_number":"interior","suburb":"Colonia"},"zip":"c\\u00f3digo postal","location":{"municipality":"Municipio","city":"Ciudad","state":"C\\u00f3digo de estado","country":"C\\u00f3digo de pa\\u00eds"},"phones":[{"type":"Facturaci\\u00f3n","phone":"+52 (33) 1522 2777, ext: 26"}]},"email":"facturas@orama.mx"},"certificate":"Cadena de certificado","taxation":"PERSONA MORAL","key":"Cadena de certificado","validity":{"start_at":"2016-04-04T00:00:00-0600","end_at":"2017-04-04T00:00:00-0600"},"locale":"cfdi","cfdi":{"api":{"class":"InterScape","url":"http:\\/\\/www.scapebusiness.mx\\/AppFactura.asmx?wsdl","user":"Usuario\\/RFC","password":"contrase\\u00f1a"}}}',
  config         = '{"banks":{"BanBajio":{"TipoDeConcepto":{"service":"###","reference":"###","name":"Nombre del concepto","account":"###"}}}}',
  `database`     = '{"invoice":{"class":"InterScape","url-externa":"https://orama.3utilities.com/AppFactura.asmx?wsdl","url":"https://172.16.110.171/AppFactura.asmx?wsdl"},"banks":{"BanBajio":{"TipoDeConcepto":{"service":"###","reference":"###","name":"Nombre del concepto","account":"###"}}},"sms":[],"pack":{"over_base":0.5}}'
WHERE id = 2
;-- -. . -..- - / . -. - .-. -.--
UPDATE customers
SET nick         = 'apack', created_at = '2016-09-06 23:11:25', updated_at = '2016-09-06 23:11:25',
  deleted_at     = NULL, invoice_number = 1, un_invoice_number = 1,
  full_name      = 'Instalación de un cliente con panel', code = '49910', short_name = 'CLIENTE',
  invoice_format = 'F-%''.05d-C', un_invoice_format = 'NC-%''.05d-C',
  web            = 'http://panel.cliente.localwamp.dev/',
  emails         = '[{"type":"Informaci\\u00f3n","email":"info@orama.com.mx"},{"type":"Contacto","email":"contacto@orama.com.mx"},{"type":"Inscripciones","email":"inscripciones@orama.com.mx"}]',
  phones         = '[{"type":"Facturaci\\u00f3n","phone":"+52 (33) 1522 2777, ext: 26"},{"type":"Administrativo","phone":"+52 (33) 1522 2777, ext: 26"},{"type":"Contacto","phone":"+52 (33) 1522 2777, ext: 26"}]',
  contract       = '{"backup":0,"historic":4.5,"active":{"0":9,"100":9,"300":8,"500":7,"750":6},"billing":{"taxid":"XAXX010101000","name":"Cliente muestra de Orama","address":{"direction":{"street":"Calle","out_number":"exterior","inside_number":"interior","suburb":"Colonia"},"zip":"c\\u00f3digo postal","location":{"municipality":"Municipio","city":"Ciudad","state":"C\\u00f3digo de estado","country":"C\\u00f3digo de pa\\u00eds"}},"phones":[{"type":"Facturaci\\u00f3n","phone":"+52 (33) 1522 2777, ext: 26"}],"emails":[{"type":"Facturaci\\u00f3n","email":"facturas@orama.com.mx"}]}}',
  invoices       = '{"taxid":"XAXX010101000","name":"Cliente muestra de Orama","address":{"direction":{"street":"Calle","out_number":"exterior","inside_number":"interior","suburb":"Colonia"},"zip":"c\\u00f3digo postal","location":{"municipality":"Municipio","city":"Ciudad","state":"C\\u00f3digo de estado","country":"C\\u00f3digo de pa\\u00eds"},"phones":[{"type":"Facturaci\\u00f3n","phone":"+52 (33) 1522 2777, ext: 26"}],"emails":[{"type":"Facturaci\\u00f3n","email":"facturas@orama.mx"}]},"public":{"taxid":"XAXX010101000","business_name":"Publico en general","address":{"direction":{"street":"Calle","out_number":"exterior","inside_number":"interior","suburb":"Colonia"},"zip":"c\\u00f3digo postal","location":{"municipality":"Municipio","city":"Ciudad","state":"C\\u00f3digo de estado","country":"C\\u00f3digo de pa\\u00eds"},"phones":[{"type":"Facturaci\\u00f3n","phone":"+52 (33) 1522 2777, ext: 26"}]},"email":"facturas@orama.mx"},"certificate":"Cadena de certificado","taxation":"PERSONA MORAL","key":"Cadena de certificado","validity":{"start_at":"2016-04-04T00:00:00-0600","end_at":"2017-04-04T00:00:00-0600"},"locale":"cfdi","cfdi":{"api":{"class":"InterScape","url":"http:\\/\\/www.scapebusiness.mx\\/AppFactura.asmx?wsdl","user":"Usuario\\/RFC","password":"contrase\\u00f1a"}}}',
  config         = '{"banks":{"BanBajio":{"TipoDeConcepto":{"service":"###","reference":"###","name":"Nombre del concepto","account":"###"}}}}',
  `database`     = '{"invoice":{"class":"InterScape","url-externa":"https://orama.3utilities.com/AppFactura.asmx?wsdl","url":"https://172.16.110.171/AppFactura.asmx?wsdl"},"banks":{"BanBajio":{"TipoDeConcepto":{"service":"###","reference":"###","name":"Nombre del concepto","account":"###"}}},"sms":[],"pack":{"over_base":0.5}}'
WHERE id = 2
;-- -. . -..- - / . -. - .-. -.--
UPDATE OCustomers_test.customers
SET nick         = 'apack', created_at = '2016-09-06 23:11:25', updated_at = '2016-09-06 23:11:25',
  deleted_at     = NULL, invoice_number = 1, un_invoice_number = 1,
  full_name      = 'Instalación de un cliente con panel', code = '49910', short_name = 'CLIENTE',
  invoice_format = 'F-%''.05d-C', un_invoice_format = 'NC-%''.05d-C',
  web            = 'http://panel.cliente.localwamp.dev/',
  emails         = '[{"type":"Informaci\\u00f3n","email":"info@orama.com.mx"},{"type":"Contacto","email":"contacto@orama.com.mx"},{"type":"Inscripciones","email":"inscripciones@orama.com.mx"}]',
  phones         = '[{"type":"Facturaci\\u00f3n","phone":"+52 (33) 1522 2777, ext: 26"},{"type":"Administrativo","phone":"+52 (33) 1522 2777, ext: 26"},{"type":"Contacto","phone":"+52 (33) 1522 2777, ext: 26"}]',
  contract       = '{"backup":0,"historic":4.5,"active":{"0":9,"100":9,"300":8,"500":7,"750":6},"billing":{"taxid":"XAXX010101000","name":"Cliente muestra de Orama","address":{"direction":{"street":"Calle","out_number":"exterior","inside_number":"interior","suburb":"Colonia"},"zip":"c\\u00f3digo postal","location":{"municipality":"Municipio","city":"Ciudad","state":"C\\u00f3digo de estado","country":"C\\u00f3digo de pa\\u00eds"}},"phones":[{"type":"Facturaci\\u00f3n","phone":"+52 (33) 1522 2777, ext: 26"}],"emails":[{"type":"Facturaci\\u00f3n","email":"facturas@orama.com.mx"}]}}',
  invoices       = '{"taxid":"XAXX010101000","name":"Cliente muestra de Orama","address":{"direction":{"street":"Calle","out_number":"exterior","inside_number":"interior","suburb":"Colonia"},"zip":"c\\u00f3digo postal","location":{"municipality":"Municipio","city":"Ciudad","state":"C\\u00f3digo de estado","country":"C\\u00f3digo de pa\\u00eds"},"phones":[{"type":"Facturaci\\u00f3n","phone":"+52 (33) 1522 2777, ext: 26"}],"emails":[{"type":"Facturaci\\u00f3n","email":"facturas@orama.mx"}]},"public":{"taxid":"XAXX010101000","business_name":"Publico en general","address":{"direction":{"street":"Calle","out_number":"exterior","inside_number":"interior","suburb":"Colonia"},"zip":"c\\u00f3digo postal","location":{"municipality":"Municipio","city":"Ciudad","state":"C\\u00f3digo de estado","country":"C\\u00f3digo de pa\\u00eds"},"phones":[{"type":"Facturaci\\u00f3n","phone":"+52 (33) 1522 2777, ext: 26"}]},"email":"facturas@orama.mx"},"certificate":"Cadena de certificado","taxation":"PERSONA MORAL","key":"Cadena de certificado","validity":{"start_at":"2016-04-04T00:00:00-0600","end_at":"2017-04-04T00:00:00-0600"},"locale":"cfdi","cfdi":{"api":{"class":"InterScape","url":"http:\\/\\/www.scapebusiness.mx\\/AppFactura.asmx?wsdl","user":"Usuario\\/RFC","password":"contrase\\u00f1a"}}}',
  config         = '{"banks":{"BanBajio":{"TipoDeConcepto":{"service":"###","reference":"###","name":"Nombre del concepto","account":"###"}}}}',
  `database`     = '{"invoice":{"class":"InterScape","url-externa":"https://orama.3utilities.com/AppFactura.asmx?wsdl","url":"https://172.16.110.171/AppFactura.asmx?wsdl"},"banks":{"BanBajio":{"TipoDeConcepto":{"service":"###","reference":"###","name":"Nombre del concepto","account":"###"}}},"sms":[],"pack":{"over_base":0.5}}'
WHERE id = 2
;-- -. . -..- - / . -. - .-. -.--
REPLACE INTO OCustomers_test.`customers` VALUES (1,'base','base','2016-10-22 02:58:20','2016-10-22 02:58:20',NULL,'Instalación base','50010','BASE','{\"responsable\":\"Nombre completo del responsable\",\"emails\":[{\"type\":\"Informaci\\u00f3n\",\"email\":\"info@orama.mx\"},{\"type\":\"Contacto\",\"email\":\"contacto@orama.mx\"},{\"type\":\"Inscripciones\",\"email\":\"inscripciones@orama\"}],\"phones\":[{\"type\":\"Facturaci\\u00f3n\",\"phone\":\"+52 (33) 1522 2777, ext: 26\"},{\"type\":\"Administrativo\",\"phone\":\"+52 (33) 1522 2777, ext: 26\"},{\"type\":\"Contacto\",\"phone\":\"+52 (33) 1522 2777, ext: 26\"}]}','[{\"range\":[3500],\"type\":1,\"description\":\"Registro de RFC\",\"periodicity\":\"Y\",\"currency\":\"MXN\",\"unit\":1},{\"range\":[0],\"type\":1,\"description\":\"Timbres fiscales\",\"periodicity\":\"Y-m\",\"currency\":\"MXN\",\"unit\":0},{\"range\":[75],\"type\":1,\"description\":\"Hosting\",\"periodicity\":\"Y-m\",\"currency\":\"USD\",\"unit\":1},{\"range\":[16],\"type\":1,\"description\":\"Acceso Europa\",\"periodicity\":\"Y-m\",\"currency\":\"USD\",\"unit\":0},{\"range\":[29],\"type\":1,\"description\":\"Acceso Asia y Oriente\",\"periodicity\":\"Y-m\",\"currency\":\"USD\",\"unit\":0},{\"range\":{\"0\":0,\"20000\":0.05},\"type\":2,\"description\":\"Emails\",\"periodicity\":\"Y-m\",\"currency\":\"MXN\",\"unit\":\"php:\\/\\/class|sql:\\/\\/function\"},{\"range\":[0],\"type\":1,\"description\":\"Respaldo\",\"periodicity\":\"Y-m\",\"currency\":\"MXN\",\"unit\":0},{\"range\":[0],\"type\":1,\"description\":\"Usuarios\",\"periodicity\":\"Y-m\",\"currency\":\"MXN\",\"unit\":0},{\"range\":{\"0\":19,\"100\":12,\"700\":9,\"2000\":6},\"type\":2,\"description\":\"Alumnos\",\"periodicity\":\"Y-m\",\"currency\":\"MXN\",\"unit\":\"php:\\/\\/class|sql:\\/\\/function\"},{\"range\":{\"0\":9,\"250\":6,\"1000\":4},\"type\":2,\"description\":\"Cliente\",\"periodicity\":\"Y-m\",\"currency\":\"MXN\",\"unit\":\"php:\\/\\/class|sql:\\/\\/function\"},{\"range\":{\"0\":2.65,\"250\":1.75,\"1000\":1.5},\"type\":3,\"description\":\"SMS por cliente\",\"periodicity\":\"Y-m\",\"currency\":\"MXN\",\"limit\":2,\"unit\":\"php:\\/\\/class|sql:\\/\\/function\"}]','{\"taxid\":\"AAA010101AAA\",\"name\":\"DEMO FISCAL BASE\",\"address\":{\"zip\":\"10000\",\"geo_point\":{\"lat\":0,\"lng\":0,\"raodZoom\":0,\"satelliteZoom\":0,\"heading\":0},\"location\":{\"municipality\":\"La Magdalena Contreras\",\"city\":\"DF\",\"state\":\"DF\",\"country\":\"MX\"},\"directions\":{\"street\":\"Calle\",\"out_number\":0,\"inside_number\":\"0\",\"suburb\":{\"zip\":\"10000\",\"name\":\"Lomas Quebradas\",\"type\":\"Colonia\",\"municipality\":\"La Magdalena Contreras\",\"state\":\"Distrito Federal\",\"city\":\"\\u00c1lvaro Obreg\\u00f3n\",\"search\":\"\\u00c1lvaro Obreg\\u00f3n, Distrito Federal, Colonia, Lomas Quebradas, La Magdalena Contreras, 10000\"}},\"phones\":[]},\"emails\":[{\"type\":\"Facturaci\\u00f3n\",\"email\":\"facturas_pruebas@plascencia.uno\"}]}','{\"invoice\":{\"class\":\"InterScape\",\"url\":\"https:\\/\\/fac104.zapto.org\\/AppFactura.asmx?wsdl\"},\"banks\":{\"BanBajio\":{\"TipoDeConcepto\":{\"service\":\"###\",\"reference\":\"###\",\"name\":\"Nombre del concepto\",\"account\":\"###\"}}},\"sms\":{}}','{\"nombre\":{\"driver\":\"mysql\",\"host\":\"localhost\",\"port\":\"3306\",\"database\":\"cliente_base\",\"username\":\"oramaLocal\",\"password\":\"OramaGeneral1\",\"charset\":\"utf8\",\"collation\":\"utf8_unicode_ci\",\"prefix\":\"\",\"strict\":false,\"engine\":null},\"installation\":{\"driver\":\"mysql\",\"host\":\"localhost\",\"port\":\"3306\",\"database\":\"apack_test\",\"username\":\"O3Apack\",\"password\":\"GedeonKcapaO3\",\"charset\":\"utf8\",\"collation\":\"utf8_unicode_ci\",\"prefix\":\"\",\"strict\":false,\"engine\":null}}'),(2,'apack','paqueteria','2016-10-22 02:58:20','2016-10-22 02:58:25',NULL,'Instalación de un cliente con panel','49910','CLIENTE','{\"responsable\":\"Nombre completo del responsable\",\"emails\":[{\"type\":\"Informaci\\u00f3n\",\"email\":\"info@orama.mx\"},{\"type\":\"Contacto\",\"email\":\"contacto@orama.mx\"},{\"type\":\"Inscripciones\",\"email\":\"inscripciones@orama\"}],\"phones\":[{\"type\":\"Facturaci\\u00f3n\",\"phone\":\"+52 (33) 1522 2777, ext: 26\"},{\"type\":\"Administrativo\",\"phone\":\"+52 (33) 1522 2777, ext: 26\"},{\"type\":\"Contacto\",\"phone\":\"+52 (33) 1522 2777, ext: 26\"}]}','[{\"range\":[3500],\"type\":1,\"description\":\"Registro de RFC\",\"periodicity\":\"Y\",\"currency\":\"MXN\",\"unit\":1},{\"range\":{\"0\":0.05},\"type\":2,\"description\":\"Paquete\",\"periodicity\":\"Y-m\",\"currency\":\"MXN\",\"unit\":\"php://class|sql://function\"},{\"range\":{\"0\":0.3},\"type\":2,\"description\":\"Registro de paquete\",\"periodicity\":\"Y-m\",\"currency\":\"MXN\",\"unit\":\"php://class|sql://function\"},{\"range\":{\"0\":0.55},\"type\":2,\"description\":\"Envío\",\"periodicity\":\"Y-m\",\"currency\":\"MXN\",\"unit\":\"php://class|sql://function\"},{\"range\":[0],\"type\":1,\"description\":\"Timbres fiscales\",\"periodicity\":\"Y-m\",\"currency\":\"MXN\",\"unit\":0},{\"range\":[55],\"type\":1,\"description\":\"Hosting\",\"periodicity\":\"Y-m\",\"currency\":\"USD\",\"unit\":1},{\"range\":{\"0\":0,\"20000\":0.05},\"type\":2,\"description\":\"Emails\",\"periodicity\":\"Y-m\",\"currency\":\"MXN\",\"unit\":\"php://class|sql://function\"},{\"range\":[0],\"type\":1,\"description\":\"Respaldo\",\"periodicity\":\"Y-m\",\"currency\":\"MXN\",\"unit\":0}]','{\"taxid\":\"AAA010101AAA\",\"name\":\"DEMO FISCAL BASE\",\"address\":{\"zip\":\"10000\",\"geo_point\":{\"lat\":0,\"lng\":0,\"raodZoom\":0,\"satelliteZoom\":0,\"heading\":0},\"location\":{\"municipality\":\"La Magdalena Contreras\",\"city\":\"DF\",\"state\":\"DF\",\"country\":\"MX\"},\"directions\":{\"street\":\"Calle\",\"out_number\":0,\"inside_number\":\"0\",\"suburb\":{\"zip\":\"10000\",\"name\":\"Lomas Quebradas\",\"type\":\"Colonia\",\"municipality\":\"La Magdalena Contreras\",\"state\":\"Distrito Federal\",\"city\":\"\\u00c1lvaro Obreg\\u00f3n\",\"search\":\"\\u00c1lvaro Obreg\\u00f3n, Distrito Federal, Colonia, Lomas Quebradas, La Magdalena Contreras, 10000\"}},\"phones\":[]},\"emails\":[{\"type\":\"Facturaci\\u00f3n\",\"email\":\"facturas@example.com\"}]}','{\"invoice\":{\"class\":\"InterScape\",\"url\":\"https:\\/\\/fac104.zapto.org\\/AppFactura.asmx?wsdl\"},\"banks\":{\"BanBajio\":{\"TipoDeConcepto\":{\"service\":\"###\",\"reference\":\"###\",\"name\":\"Nombre del concepto\",\"account\":\"###\"}}},\"sms\":[],\"pack\":{\"over_base\":0.5}}','{\"nombre\":{\"driver\":\"mysql\",\"host\":\"localhost\",\"port\":\"3306\",\"database\":\"cliente_base\",\"username\":\"oramaLocal\",\"password\":\"OramaGeneral1\",\"charset\":\"utf8\",\"collation\":\"utf8_unicode_ci\",\"prefix\":\"\",\"strict\":false,\"engine\":null},\"installation\":{\"driver\":\"mysql\",\"host\":\"localhost\",\"port\":\"3306\",\"database\":\"apack_test\",\"username\":\"O3Apack\",\"password\":\"GedeonKcapaO3\",\"charset\":\"utf8\",\"collation\":\"utf8_unicode_ci\",\"prefix\":\"\",\"strict\":false,\"engine\":null}}')