#!/bin/sh

# Buscar un archivo con find
# Obtiene los parámetros de la función
file="$1"
shift
dir="$1"

# Si no se especifica el directorio objetivo, lo establece en el directorio actual
if [ -z "$dir" ] || [ ! -d "$dir" ] ; then
  dir="."
else
  shift
fi

extras=$@

# Si no se especifica el directorio objetivo, lo establece en el directorio actual
if [ -z "$extras" ]; then
  extras="-type f"
fi

# Realiza la búsqueda con find
echo "find '${dir}' -name '${file}' ${extras}"
find "$dir" -name "$file" $extras

