#!/usr/bin/env bash

#https://github.com/LytixDev/tomatoshell/tree/main
#https://gist.github.com/leo-pfeiffer/3e19a8c2c4f6f91f9b17b9f6bc8e0328
#https://github.com/kevinschoon/pomo
#sleep 300 && notify-send "back to work"  # a short, 5-minute break
#sleep 900 && notify-send "back to work"  # a long, 15-minute break

min=${1:-${POMODORO_MIN:-25}}
shift
sec=$((min * 60))
timeBreak=$((sec / 5))
msgBreakTime="${*:-'Pomodoro: Take a break'} ($((timeBreak / 60)) min)"
msgWorkTime="Pomodoro: Back to work; Better, faster, stronger!"

echo "Pomodoro active: ${min} min and repo $((timeBreak / 60)) min"

while true; do
    sleep "${sec:?1}"
    notify-send -u low -t "$((timeBreak * 750))" -a pomo "${msgBreakTime}"
    sleep "${timeBreak:?1}"
    notify-send -u normal -t "$((timeBreak * 750))" -a pomo "${msgWorkTime}"
    exit 0
done &

