#!/usr/bin/env bash

# Initialize
printf "$$" > ~/.cache/pidofbar
sec=0

# Update functions
update_cpu() {
  cpu=$(awk '{print $1}' /proc/loadavg)
}

update_memory() {
  memory=$(free -h | awk 'NR==2 {print $3}')
}

update_time() {
  time=$(date '+%Y-%m-%d (%a W%W) %H:%M')
}

update_weather() {
  weather=$(curl -s "wttr.in/dallas?format=1" | cut -c1)
}

update_bat() {
  if [[ -e /sys/class/power_supply/BAT1/status ]]; then
    bat_status=$(< /sys/class/power_supply/BAT1/status)
    if [[ -e /sys/class/power_supply/BAT1/capacity ]]; then
      bat_capacity=$(< /sys/class/power_supply/BAT1/capacity)
      bat=" $bat_capacity%"
    else
      bat="$bat_status"
    fi
  fi
}

update_vol() {
  vol="$(pactl list sinks | awk '/Volume:/ {print $5}' | head -n 1 | tr -d '%')%"
}

update_backlight() {
  if [[ -e /sys/class/backlight/intel_backlight/actual_brightness ]]; then
    actual_brightness=$(< /sys/class/backlight/intel_backlight/actual_brightness)
    max_brightness=$(< /sys/class/backlight/intel_backlight/max_brightness)
    backlight="☀$((actual_brightness * 100 / max_brightness))%"
  else
    backlight=""
  fi
}

update_layout() {
  layout=$(setxkbmap -query | awk '/layout*/ { print $2 }')
}
# Display function
display() {
  status=""
  [[ -n "$layout" ]] && status+="$layout "
  [[ -n "$bat" ]] && status+="$bat "
#  [[ -n "$backlight" ]] && status+="$backlight "
  [[ -n "$vol" ]] && status+="$vol "
  [[ -n "$time" ]] && status+="$time"
  xsetroot -name "$status"
}

# Set up signal handlers
trap "update_vol; display" "RTMIN"
trap "update_backlight; display" "RTMIN+1"
trap "update_bat; display" "RTMIN+2"

# Initial updates
update_vol
update_backlight
update_bat
update_layout

# Main loop
while true; do
  case $((sec % 60)) in
    0)
      update_layout
      update_bat
      ;;
    [1-5]) 
      update_time
      update_vol
      display
      ;;
  esac
  sleep 1
  sec=$((sec + 1))
done &

