#!/bin/sh

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

if [ -s "$NVM_DIR/nvm.sh" ] ; then
  export NVM_DIR="$HOME/.nvm"
  cdnvm() {
      command cd "$@" || return $?
      if [[ -f ./.nvmrc ]]; then
          declare nvm_version
          nvm_version=$(<./.nvmrc)

          declare locally_resolved_nvm_version
          # `nvm ls` will check all locally-available versions
          # If there are multiple matching versions, take the latest one
          # Remove the `->` and `*` characters and spaces
          # `locally_resolved_nvm_version` will be `N/A` if no local versions are found
          locally_resolved_nvm_version=$(nvm ls --no-colors "$nvm_version" | tail -1 | tr -d '\->*' | tr -d '[:space:]')

          # If it is not already installed, install it
          # `nvm install` will implicitly use the newly-installed version
          if [[ "$locally_resolved_nvm_version" == "N/A" ]]; then
              nvm install "$nvm_version";
          elif [[ $(nvm current) != "$locally_resolved_nvm_version" ]]; then
              nvm use "$nvm_version";
          fi
      fi
  }

  alias cd='cdnvm'
fi
