#!/usr/bin/env bash

#https://github.com/LytixDev/tomatoshell/tree/main
#https://gist.github.com/leo-pfeiffer/3e19a8c2c4f6f91f9b17b9f6bc8e0328
#https://github.com/kevinschoon/pomo
#sleep 300 && notify-send "back to work"  # a short, 5-minute break
#sleep 900 && notify-send "back to work"  # a long, 15-minute break
function pomo() {
    arg1=$1
    shift
    args="$*"

    min=${arg1:?Example: pomo 15 Take a break}
    sec=$((min * 60))
    msg="${args:?Example: pomo 15 Take a break}"

    while true; do
        date '+%H:%M' &&
        sleep "${sec:?}" &&
        notify-send -u critical -t 0 -a pomo "${msg:?}"
        #spd-say "${msg:?}"
    done
}

#nohup pomo.sh 20 &
